version: '3.8'

services:
  bitminti:
    build: .
    container_name: bitminti-node
    ports:
      - "13337:13337"  # P2P
      - "8332:8332"    # RPC
    volumes:
      - bitminti-data:/bitminti-data
    restart: unless-stopped
    environment:
      - RPC_USER=admin
      - RPC_PASSWORD=admin
    networks:
      - bitminti-network

volumes:
  bitminti-data:
    driver: local

networks:
  bitminti-network:
    driver: bridge

